# Generated by Django 4.2 on 2025-11-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Device', max_length=100)),
                ('api_key', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnergyReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voltage', models.FloatField(help_text='Voltage in Volts (V)')),
                ('current', models.FloatField(help_text='Current in Amperes (A)')),
                ('power', models.FloatField(help_text='Power in Watts (W)')),
                ('energy', models.FloatField(help_text='Cumulative energy in kWh')),
                ('frequency', models.FloatField(help_text='Frequency in Hertz (Hz)')),
                ('power_factor', models.FloatField(help_text='Power Factor (0-1)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='monitoring.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_POWER', 'High Power Consumption'), ('LOW_VOLTAGE', 'Low Voltage'), ('HIGH_VOLTAGE', 'High Voltage'), ('LOW_PF', 'Low Power Factor'), ('DEVICE_OFFLINE', 'Device Offline')], max_length=20)),
                ('message', models.TextField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='monitoring.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['device', '-timestamp'], name='monitoring__device__ba38d6_idx'),
        ),
        migrations.AddIndex(
            model_name='energyreading',
            index=models.Index(fields=['timestamp'], name='monitoring__timesta_06cdc5_idx'),
        ),
    ]
